// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyHub.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudyHub.Models.ClassGroup", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("ClassGroups");
                });

            modelBuilder.Entity("StudyHub.Models.ReviewFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.Property<string>("TermSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TermId");

                    b.ToTable("ReviewFlags");
                });

            modelBuilder.Entity("StudyHub.Models.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("StudyHub.Models.SubjectClassGroup", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClassGroupCode")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SubjectId", "ClassGroupCode");

                    b.HasIndex("ClassGroupCode");

                    b.ToTable("SubjectClassGroups");
                });

            modelBuilder.Entity("StudyHub.Models.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("StudyHub.Models.TermSubject", b =>
                {
                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TermId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TermSubjects");
                });

            modelBuilder.Entity("StudyHub.Models.ReviewFlag", b =>
                {
                    b.HasOne("StudyHub.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudyHub.Models.Term", "Term")
                        .WithMany("ReviewFlags")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("StudyHub.Models.SubjectClassGroup", b =>
                {
                    b.HasOne("StudyHub.Models.ClassGroup", "ClassGroup")
                        .WithMany("SubjectClassGroups")
                        .HasForeignKey("ClassGroupCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyHub.Models.Subject", "Subject")
                        .WithMany("SubjectClassGroups")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroup");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudyHub.Models.TermSubject", b =>
                {
                    b.HasOne("StudyHub.Models.Subject", "Subject")
                        .WithMany("TermSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudyHub.Models.Term", "Term")
                        .WithMany("TermSubjects")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("StudyHub.Models.ClassGroup", b =>
                {
                    b.Navigation("SubjectClassGroups");
                });

            modelBuilder.Entity("StudyHub.Models.Subject", b =>
                {
                    b.Navigation("SubjectClassGroups");

                    b.Navigation("TermSubjects");
                });

            modelBuilder.Entity("StudyHub.Models.Term", b =>
                {
                    b.Navigation("ReviewFlags");

                    b.Navigation("TermSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
